/*
 * Calculator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Operation struct {

	Number1 int64 `json:"number1"`

	Number2 int64 `json:"number2"`
}

type Result struct {

	Result int64 `json:"Result"`
}

